//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWSHackathonClient.PWS_Proxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/PWSHackathonWCF")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Line4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMail {
            get {
                return this.EMailField;
            }
            set {
                if ((object.ReferenceEquals(this.EMailField, value) != true)) {
                    this.EMailField = value;
                    this.RaisePropertyChanged("EMail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line1 {
            get {
                return this.Line1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line1Field, value) != true)) {
                    this.Line1Field = value;
                    this.RaisePropertyChanged("Line1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line2 {
            get {
                return this.Line2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line2Field, value) != true)) {
                    this.Line2Field = value;
                    this.RaisePropertyChanged("Line2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line3 {
            get {
                return this.Line3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line3Field, value) != true)) {
                    this.Line3Field = value;
                    this.RaisePropertyChanged("Line3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Line4 {
            get {
                return this.Line4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Line4Field, value) != true)) {
                    this.Line4Field = value;
                    this.RaisePropertyChanged("Line4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelephoneNumber {
            get {
                return this.TelephoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneNumberField, value) != true)) {
                    this.TelephoneNumberField = value;
                    this.RaisePropertyChanged("TelephoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PWS_Proxy.IAddressService")]
    public interface IAddressService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAddress", ReplyAction="http://tempuri.org/IAddressService/GetAddressResponse")]
        PWSHackathonClient.PWS_Proxy.Address GetAddress(string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAddress", ReplyAction="http://tempuri.org/IAddressService/GetAddressResponse")]
        System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> GetAddressAsync(string postcode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/CreateAddress", ReplyAction="http://tempuri.org/IAddressService/CreateAddressResponse")]
        PWSHackathonClient.PWS_Proxy.Address CreateAddress(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/CreateAddress", ReplyAction="http://tempuri.org/IAddressService/CreateAddressResponse")]
        System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> CreateAddressAsync(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/DeleteAddress", ReplyAction="http://tempuri.org/IAddressService/DeleteAddressResponse")]
        PWSHackathonClient.PWS_Proxy.Address DeleteAddress(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/DeleteAddress", ReplyAction="http://tempuri.org/IAddressService/DeleteAddressResponse")]
        System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> DeleteAddressAsync(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/UpdateAddress", ReplyAction="http://tempuri.org/IAddressService/UpdateAddressResponse")]
        PWSHackathonClient.PWS_Proxy.Address UpdateAddress(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/UpdateAddress", ReplyAction="http://tempuri.org/IAddressService/UpdateAddressResponse")]
        System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> UpdateAddressAsync(PWSHackathonClient.PWS_Proxy.Address address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAllAddresses", ReplyAction="http://tempuri.org/IAddressService/GetAllAddressesResponse")]
        PWSHackathonClient.PWS_Proxy.Address[] GetAllAddresses();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAddressService/GetAllAddresses", ReplyAction="http://tempuri.org/IAddressService/GetAllAddressesResponse")]
        System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address[]> GetAllAddressesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAddressServiceChannel : PWSHackathonClient.PWS_Proxy.IAddressService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServiceClient : System.ServiceModel.ClientBase<PWSHackathonClient.PWS_Proxy.IAddressService>, PWSHackathonClient.PWS_Proxy.IAddressService {
        
        public AddressServiceClient() {
        }
        
        public AddressServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PWSHackathonClient.PWS_Proxy.Address GetAddress(string postcode) {
            return base.Channel.GetAddress(postcode);
        }
        
        public System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> GetAddressAsync(string postcode) {
            return base.Channel.GetAddressAsync(postcode);
        }
        
        public PWSHackathonClient.PWS_Proxy.Address CreateAddress(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.CreateAddress(address);
        }
        
        public System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> CreateAddressAsync(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.CreateAddressAsync(address);
        }
        
        public PWSHackathonClient.PWS_Proxy.Address DeleteAddress(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.DeleteAddress(address);
        }
        
        public System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> DeleteAddressAsync(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.DeleteAddressAsync(address);
        }
        
        public PWSHackathonClient.PWS_Proxy.Address UpdateAddress(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.UpdateAddress(address);
        }
        
        public System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address> UpdateAddressAsync(PWSHackathonClient.PWS_Proxy.Address address) {
            return base.Channel.UpdateAddressAsync(address);
        }
        
        public PWSHackathonClient.PWS_Proxy.Address[] GetAllAddresses() {
            return base.Channel.GetAllAddresses();
        }
        
        public System.Threading.Tasks.Task<PWSHackathonClient.PWS_Proxy.Address[]> GetAllAddressesAsync() {
            return base.Channel.GetAllAddressesAsync();
        }
    }
}
